-- see https://web.archive.org/web/20240718080538/https://www.koyeb.com/tutorials/using-spring-authorization-server-as-an-auth-solution-on-koyeb
-- auth-koyeb/auth-server/src/main/resources/schema.sql

-- users
create table if not exists users
(
    username varchar(200) not null primary key,
    password varchar(500) not null,
    enabled  boolean      not null,
    constraint username UNIQUE (username)
);

-- authorities
create table if not exists authorities
(
    username  varchar(200) not null,
    authority varchar(50)  not null,
    constraint fk_authorities_users foreign key (username) references users (username),
    constraint username_authority UNIQUE (username, authority)
    );
create unique index if not exists  ix_auth_username on authorities (username,authority);

-- groups
create table if not exists  groups (
                                       id bigint generated by default as identity(start with 1) primary key,
    group_name varchar(50) not null,
    constraint group_name UNIQUE (group_name)
    );

create table if not exists  group_authorities (
                                                  group_id bigint not null,
                                                  authority varchar(50) not null,
    constraint authority UNIQUE (authority),
    constraint fk_group_authorities_group foreign key(group_id) references groups(id)
    );

create table if not exists  group_members (
                                              id bigint generated by default as identity(start with 1) primary key,
    username varchar(50) not null,
    group_id bigint not null,
    constraint username_group_id UNIQUE (username, group_id),
    constraint fk_group_members_group foreign key(group_id) references groups(id)
    );

-- DROPPING THE API WITH CASCADE takes out tables too
-- drop schema api cascade ;
-- drop table users cascade ;
-- drop table authorities cascade ;
-- drop table groups cascade ;
-- drop table group_members cascade ;
-- drop index ix_auth_username ;


